spring:
  application:
    name: demo
  mvc:
    view:
      throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: bbs
    password: bbs
  web:
    resources:
      add-mappings: true
  servlet:
    multipart:
      enabled: true
      location: C:\\multipart\\upload_file\\temp
      max-file-size: 100MB
      max-request-size: 200MB
server:
  port: 8111

upload.path: C:\\multipart\\upload_file

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr([rowNumber]: %line){red} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  file:
    name: C:\app-log\log.txt
    append: true
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off
    org.springframework.web: error
  logback:
    rollingpolicy:
      file-name-pattern: C:\\app-log\\old\\log-%d{yyyy-MM-dd}_%i.txt
      max-file-size: 100MB
      max-history: 30

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
        
